#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello_world": "00_core.ipynb"}

modules = ["core.py"]

git_url = "https://github.com/cbjuan/nbdev_test/tree/master/"

def custom_doc_links(name): return None